### ISSUE TITLE
Replaced `<body>` tag

### ISSUE THREAD

**Issue by phonzammi** [hi-ogawa/experiments#48]
Hi @hi-ogawa,
I hope I'm not interrupting you. Just wondering did you intentionally replaced the open `<body>` tag ? 
I saw there is no opening `<body>` tag anymore here `view-source:https://vue-server-demo.hiro18181.workers.dev/`.

https://github.com/hi-ogawa/experiments/blob/527f0e6e3d9bcba5fe09189f4ba6782f85586c82/vue-server/src/demo/entry-server.tsx#L28

**Comment by hi-ogawa** [comment]
Oh, nice find. That's not what I intended at all and I forgot to put `<body>` back.
I will fix it soon in https://github.com/hi-ogawa/experiments/pull/49. Thanks for pointing it out!
